[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ–](bold red) "

[time]
time_format = "%T"
style = "bright-white"
format = "ğŸ•™ $time($style) "
disabled = false

[[battery.display]]
threshold = 1
style = "bold red"

[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
format = "ğŸ“‚ [$path]($style)[$lock_symbol]($lock_style) "
style = "bold italic #98c379"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic #98c379"

[status]
symbol = "ğŸ”´"
style = "#e06c75"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[java]
format = ""

[nodejs]
format = ""

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 10
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ¤· Ã—${count} "
stashed = "ğŸ“¦"
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ‘… Ã—${count} "
deleted = "ğŸ—‘ï¸ Ã—${count} "
